! Программа задания  деформаций функциями, соответствующими винтовой траектории деформаций
! Для упруго-пласт. плоско-напряж. элемента
! Размерность мм, МПа

/CLEAR,NOSTART
/FILENAME, biso


*DIM, param_buf, ARRAY, 1 ! Создаем временный массив для чтения из одного элемента

*VREAD, param_buf(1), filter_step, txt, , , 
(F20.0) ! указывает команде *VREAD, что ожидаем считать вещественное число в следующих 20 символах из строки
filter_step = param_buf(1)

*VREAD, param_buf(1), steps_n1, txt, , , 
(F20.0)
N_stage1 = NINT(param_buf(1)) ! Округляем до целого

*VREAD, param_buf(1), steps_n2, txt, , , 
(F20.0)
N_stage2 = NINT(param_buf(1)) ! Округляем до целого

*VREAD, param_buf(1), nu, txt, , , 
(F20.0)
nu = param_buf(1)

*VREAD, param_buf(1), a, txt, , , 
(F20.0)
a = param_buf(1) ! Шаг винтовой линии для эксперимента

*VREAD, param_buf(1), c, txt, , , 
(F20.0)
cc = param_buf(1) ! Для эксперимента П.29

*VREAD, param_buf(1), n_turns, txt, , , 
(F20.0)
nv = NINT(param_buf(1)) ! Количество витков

*DEL, param_buf ! Удаляем буфер


size=1 ! Размер элемента в мм
pi=acos(-1)

epsy00=0.005 ! В экспернименте это величина epsz*=0.005, одинаковая для всех экспериментов
epsy0=epsy00+cc ! Величина деформации растяжения по y


/PREP7
ET,1,PLANE182
MP,EX,1,2.05e5 ! МПа
MP,PRXY,1,nu
TB,BISO,1,1,2
TBTEMP,0
TBDATA,,360,10000,,,, !МПа Сталь 45

! узлы элемента
N,1,0,0,0
N,2,size,0,0
N,3,size,size,0
N,4,0,size,0
E,1,2,3,4


/SOLU

! 1-ый шаг - решение с нулевыми граничными условиями
D,ALL,ALL,0
SOLVE ! Нулевая точка
OUTRES,ALL,ALL

! 1-ый этап - одноосное деформирование по у до величины epsy0
d0=epsy0/N_stage1 ! Прирост деформации на каждом шаге


! Жестко закрепляем узел 1
D,1,UX,0 
D,1,UY,0

*DO,i,1,N_stage1 ,1

	! Целевые деформации на текущем шаге i
	epsx = 0
	epsy = d0*i
	tauxy = 0

	! Вычисляем ВСЕ компоненты перемещений по формулам (3.4)
	! ux = epsx*x + tauxy*y
	! uy = epsy*y
    
	! Узел 2 (x=size, y=0)
	d2x = epsx*size + tauxy*0
	d2y = epsy*0
    
	! Узел 3 (x=size, y=size)
	d3x = epsx*size + tauxy*size
	d3y = epsy*size
    
	! Узел 4 (x=0, y=size)
	d4x = epsx*0 + tauxy*size
	d4y = epsy*size

	! Прикладываем ВСЕ вычисленные перемещения ко ВСЕМ свободным узлам
	D,2,UX,d2x
	D,2,UY,d2y
	
	D,3,UX,d3x
	D,3,UY,d3y
	
	D,4,UX,d4x
	D,4,UY,d4y
	
	TIME,i+1
	NSUBST,100,0,0
	AUTOTS,1
	SOLVE
*ENDDO

! 2-ой этап - деформирование по винтовой линии
dalf = (2*pi*nv) / N_stage2 ! Изменение угла на каждом шаге

*DO,j,1,N_stage2,1

	alf=dalf*j
	epsx = sqrt(3)/2*a*(alf/(2*pi)) - 1/2*cc*(cos(alf)-1) ! соответствует eps_tetta
	epsy=cc*(cos(alf)-1)+epsy0 ! соответствует eps_z
	tauxy=-2*sqrt(3)/2*cc*sin(alf) ! соответствует gamma_tetta_z=2*eps_tetta_z

	! Узел 2 (x=size, y=0)
	d2x = epsx*size + tauxy*0
	d2y = epsy*0
    
	! Узел 3 (x=size, y=size)
	d3x = epsx*size + tauxy*size
	d3y = epsy*size
    
	! Узел 4 (x=0, y=size)
	d4x = epsx*0 + tauxy*size
	d4y = epsy*size

	D,2,UX,d2x
	D,2,UY,d2y
	
	D,3,UX,d3x
	D,3,UY,d3y
	
	D,4,UX,d4x
	D,4,UY,d4y

	TIME,j+N_stage1+1
	NSUBST,100,0,0
	AUTOTS,1 !Включить автомат. шаг расчета

	SOLVE
*ENDDO

FINISH


/POST26

*GET, ActiveJob, ACTIVE, 0, JOBNAM
FILE, ActiveJob, 'rst'

NUMVAR, 50

! Объявление деформаций
ESOL,2,1,3,EPEL,X,
ESOL,3,1,3,EPPL,X,
ADD,4,2,3, , , , ,1,1,1, ! полная деформация eps_xx

ESOL,5,1,3,EPEL,Y,
ESOL,6,1,3,EPPL,Y,
ADD,7,5,6, , , , ,1,1,1, ! полная деформация eps_yy

ESOL,8,1,3,EPEL,XY,
ESOL,9,1,3,EPPL,XY,
ADD,10,8,9, , , , ,1,1,1, ! полная деформация eps_xy

ESOL,11,1,3,EPEL,Z,
ESOL,12,1,3,EPPL,Z,
ADD,13,11,12, , , , ,1,1,1, ! полная деформация eps_zz

! Объявление напряжений
ESOL,14,1,3,S,X,
ESOL,15,1,3,S,Y,
ESOL,16,1,3,S,XY,
ESOL,17,1,3,S,EQV, ! интенсивность напряжений

XVAR,1 ! строим графики от времени

PLVAR,4,7,10,13, , , , , , , ! график деформаций

ESOL,18,1,3,EPPL,EQV, ! интенсивность деформаций
ESOL,19,1,3,NL,EPEQ, ! параметр Одквиста

STORE,MERGE ! Загружаем все объявленные переменные данными

*GET, n_raw, VARI, 1, NSETS ! Достаем количество ВСЕХ подшагов расчета и помещаем в n_raw
*DIM, t_raw, ARRAY, n_raw ! Создаем массив для времени длины в n_raw
VGET, t_raw(1), 1 ! Заполняем массив с первого элемента переменной 1 - TIME

*DIM, keep_flag, ARRAY, n_raw ! Создаем массив-маску длины n_raw
*VFILL, keep_flag(1), RAMP, 0, 0 ! Заполняем массив-маску нулями

! Всегда берем первую точку
keep_flag(1) = 1
count = 1
last_saved_time = t_raw(1)

*DO, i, 2, n_raw, 1
    curr_time = t_raw(i)
    delta = curr_time - last_saved_time ! Вычисляем разницу с последней сохраненной точкой

    *IF, delta, GE, filter_step, THEN ! Если разница больше или равна шагу фильтрации
        keep_flag(i) = 1  
        count = count + 1 
        last_saved_time = curr_time ! Обновляем время последней записи
    *ENDIF
*ENDDO

*DIM, buf, ARRAY, n_raw ! Создаем буффер длины n_raw

! Создаем массивы для выходных данных длины count
*DIM, v_time, ARRAY, count
*DIM, v_epelx, ARRAY, count
*DIM, v_epplx, ARRAY, count
*DIM, v_eptox, ARRAY, count
*DIM, v_epely, ARRAY, count
*DIM, v_epply, ARRAY, count
*DIM, v_eptoy, ARRAY, count
*DIM, v_epelxy, ARRAY, count
*DIM, v_epplxy, ARRAY, count
*DIM, v_eptoxy, ARRAY, count
*DIM, v_epelz, ARRAY, count
*DIM, v_epplz, ARRAY, count
*DIM, v_eptoz, ARRAY, count
*DIM, v_sx, ARRAY, count
*DIM, v_sy, ARRAY, count
*DIM, v_sxy, ARRAY, count
*DIM, v_seqv, ARRAY, count
*DIM, v_eppleqv, ARRAY, count
*DIM, v_nlepeq, ARRAY, count

! Заполняем массив v_time операцией (t_raw & keep_flag)
! Оставляет только те элементы из t_raw, на месте которых в keep_flag стоит 1
*VMASK, keep_flag(1)
*VFUN, v_time(1), COMP, t_raw(1)

VGET, buf(1), 2 ! заполняем буффер второй переменной
*VMASK, keep_flag(1)
*VFUN, v_epelx(1), COMP, buf(1)

VGET, buf(1), 3
*VMASK, keep_flag(1)
*VFUN, v_epplx(1), COMP, buf(1)

VGET, buf(1), 4
*VMASK, keep_flag(1)
*VFUN, v_eptox(1), COMP, buf(1)

VGET, buf(1), 5
*VMASK, keep_flag(1)
*VFUN, v_epely(1), COMP, buf(1)

VGET, buf(1), 6
*VMASK, keep_flag(1)
*VFUN, v_epply(1), COMP, buf(1)

VGET, buf(1), 7
*VMASK, keep_flag(1)
*VFUN, v_eptoy(1), COMP, buf(1)

VGET, buf(1), 8
*VMASK, keep_flag(1)
*VFUN, v_epelxy(1), COMP, buf(1)

VGET, buf(1), 9
*VMASK, keep_flag(1)
*VFUN, v_epplxy(1), COMP, buf(1)

VGET, buf(1), 10
*VMASK, keep_flag(1)
*VFUN, v_eptoxy(1), COMP, buf(1)

VGET, buf(1), 11
*VMASK, keep_flag(1)
*VFUN, v_epelz(1), COMP, buf(1)

VGET, buf(1), 12
*VMASK, keep_flag(1)
*VFUN, v_epplz(1), COMP, buf(1)

VGET, buf(1), 13
*VMASK, keep_flag(1)
*VFUN, v_eptoz(1), COMP, buf(1)

VGET, buf(1), 14
*VMASK, keep_flag(1)
*VFUN, v_sx(1), COMP, buf(1)

VGET, buf(1), 15
*VMASK, keep_flag(1)
*VFUN, v_sy(1), COMP, buf(1)

VGET, buf(1), 16
*VMASK, keep_flag(1)
*VFUN, v_sxy(1), COMP, buf(1)

VGET, buf(1), 17
*VMASK, keep_flag(1)
*VFUN, v_seqv(1), COMP, buf(1)

VGET, buf(1), 18
*VMASK, keep_flag(1)
*VFUN, v_eppleqv(1), COMP, buf(1)

VGET, buf(1), 19
*VMASK, keep_flag(1)
*VFUN, v_nlepeq(1), COMP, buf(1)

*CFOPEN, %ActiveJob%, csv ! Открываем CSV файл для записи

! Записываем заголовок
*VWRITE,'Time','EPEL_TT','EPPL_TT','EPTO_TT','EPEL_ZZ','EPPL_ZZ','EPTO_ZZ','EPEL_TZ','EPPL_TZ','EPTO_TZ','EPEL_RR','EPPL_RR','EPTO_RR','S_TT','S_ZZ','S_TZ','S_EQV','EPPL_EQV','NL_EPEQ'
(A,',',A,',',A,',',A,',',A,',',A,',',A,',',A,',',A,',',A,',',A,',',A,',',A,',',A,',',A,',',A,',',A,',',A,',',A)

! Записываем данные
*VWRITE, v_time(1), v_epelx(1), v_epplx(1), v_eptox(1), v_epely(1), v_epply(1), v_eptoy(1), v_epelxy(1), v_epplxy(1), v_eptoxy(1), v_epelz(1), v_epplz(1), v_eptoz(1), v_sx(1), v_sy(1), v_sxy(1), v_seqv(1), v_eppleqv(1), v_nlepeq(1)
(E14.7,',',E14.7,',',E14.7,',',E14.7,',',E14.7,',',E14.7,',',E14.7,',',E14.7,',',E14.7,',',E14.7,',',E14.7,',',E14.7,',',E14.7,',',E14.7,',',E14.7,',',E14.7,',',E14.7,',',E14.7,',',E14.7)

*CFCLOS

*DEL, ALL ! чистим все массивы
FINISH
